### ISSUE TITLE
Effort (Timeslice)

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#14]
Zu implementieren wenn:
* #1 (Employee)
* #13 (ProjectPosition)

## TODO
- [x] Backend-Implementation fertig
- [x] Frontend-Implementation fertig
- [x] DB-Migrationsskript aktualisiert

## Abklären
- [x] Neues Feld für detaillierte Beschreibung, was in diesem Effort geleistet wurde?

**Comment by andyundso** [comment]
Feedback von Andi: Detailliertes Feld wird nicht benötigt, auch nicht für interne Auswertungen. Die momentanen Projekt-Kommentare reichen für diesen Zweck.

**Comment by andyundso** [comment]
Tracking von Frontend passiert in #29.
