### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#15]
Zu implementieren wenn:
* #1 (Employee)
* #3 (RateGroup)
* #7 (Customer)
* #9 (Address)

## TODO
- [x] Backend-Implementation fertig
- [x] Frontend-Implementation fertig
  - [x] Neues Feature: Wenn der Status auf "Bestätigt" wechselt, werden alle Inputfelder ausser dem Status deaktiviert - die Offerte ist quasi eingefroren. 
  - [x] Neu wird auch das Restbudget auf dem Projekt dynamisch anhand der Offerte berechnet.
  - [x] Print Button
  - [x] Navigation zu verbundenen Projekten/Rechnungen
  - [x] Breakdown Berechnung
  - [x] Services als Popup editieren
- [x] DB-Migrationsskript aktualisiert

**Comment by tourn** [comment]
Neues Feature: Wenn der Status auf "Bestätigt" wechselt, werden alle Inputfelder ausser dem Status deaktiviert - die Offerte ist quasi eingefroren. Neu wird auch das Restbudget auf dem Projekt dynamisch anhand der Offerte berechnet.

**Comment by andyundso** [comment]
Breakdown, Project ID sowie Invoice IDs werden nun aus dem Backend geliefert.
