### ISSUE TITLE
EmployeeSetting

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#23]
Zu implementieren wenn:
* #1 (Employee)

## TODO
- [ ] Backend-Implementation fertig
- [ ] Frontend-Implementation fertig
- [ ] DB-Migrationsskript aktualisiert
