### ISSUE TITLE
Holiday

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/betterDime#25]
## TODO
- [ ] Backend-Implementation fertig
- [ ] Frontend-Implementation fertig
- [ ] DB-Migrationsskript aktualisiert

**Comment by andyundso** [comment]
duplicate of #24.
